# fly.toml file generated for finance-app on 2021-12-13T15:11:09-08:00

app = "finance-app"


[build]
  builder = 'https://github.com/BernardN38/buildpack-test'
  buildpacks = ["https://github.com/BernardN38/buildpack-test"]

[env]
  PORT = "8000"
